export const ADD_ANIME = 'add_anime'
export const POP_FORM = 'pop_form'
export const UNDO_FORM = 'undo_form'
export const CONNECT_TO_MAL = 'connect_to_mal'
export const DISCONNECT_FROM_MAL = 'disconnect_from_mal'
